# frozen_string_literal: true
source "https://rubygems.org"

group :development, :test do
  gem "rake"

  gem "cancancan"
  gem "pundit"

  gem "draper"
  gem "devise"

  gem "rails", "~> 7.0.0"

  gem "sprockets-rails"
  gem "sassc-rails"

  gem "cssbundling-rails"
  gem "jsbundling-rails"
end

group :test do
  gem "cuprite", ">= 0.15"
  gem "capybara"
  gem "webrick", ">= 1.8.2"

  gem "simplecov", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "simplecov-cobertura", ">= 3.0.0", require: false
  gem "cucumber-rails", ">= 3.0.0", require: false
  gem "cucumber"
  gem "database_cleaner"
  gem "launchy"
  gem "parallel_tests"
  gem "rspec-rails"
  gem "sqlite3", platform: :mri

  # Translations
  gem "i18n-tasks", ">= 1.0.14"
  gem "i18n-spec"
  gem "rails-i18n" # Provides default i18n for many languages
end

gemspec path: "../.."
