# frozen_string_literal: true
source "https://rubygems.org"

group :development, :test do
  gem "rake"

  gem "cancancan"
  gem "pundit"
  gem "jruby-openssl", platform: :jruby

  gem "draper"
  gem "devise"

  gem "rails", "~> 7.0.8", ">= 7.0.8.1"
  gem "activerecord-jdbcsqlite3-adapter", platform: :jruby

  gem "sprockets-rails"
  gem "sassc-rails"

  gem "cssbundling-rails", ">= 1.4.0"
  gem "jsbundling-rails", ">= 1.2.2"
end

group :test do
  gem "cuprite", ">= 0.15"
  gem "capybara", ">= 3.40.0"
  gem "webrick"

  gem "simplecov", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "simplecov-cobertura", require: false
  gem "cucumber-rails", ">= 3.0.0", require: false
  gem "cucumber"
  gem "database_cleaner"
  gem "launchy"
  gem "parallel_tests"
  gem "rspec-rails", ">= 6.0.4"
  gem "sqlite3", platform: :mri

  # Translations
  gem "i18n-tasks"
  gem "i18n-spec"
  gem "rails-i18n" , ">= 7.0.9" # Provides default i18n for many languages
end

gemspec path: "../.."
